name: 'Use Python Dependencies'

description: 'Sets up Python and installs project dependencies.'

runs:
  using: 'composite'
  steps:
    - name: '🔧 Setup Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          pip-requirements.txt
          dev-requirements.txt
          requirements.txt
    - name: '🔧 Configure pip'
      run: pip install -r pip-requirements.txt
      shell: bash
    - name: '🛠️ Install development dependencies'
      run: pip install -r dev-requirements.txt
      shell: bash
    - name: '📦 Install app dependencies'
      run: pip install -r requirements.txt
      shell: bash
