from enum import Enum


class ErrorCodeEnum(Enum):
    # auth
    UNAUTHORIZED_ERROR = 4001
    INVALID_GITHUB_OAUTH_COOKIE_ERROR = 4002
    GITHUB_OAUTH_COOKIE_NOT_FOUND_ERROR = 4003
    # chat
    CHAT_USER_CANCELLED_ERROR = 1000
    # general
    INTERNAL_SERVER_ERROR = 5000
    # agents
    MODEL_NOT_SUPPORTED_ERROR = 6000
    MESSAGE_ROLE_NOT_SUPPORTED_ERROR = 6001
    # templates
    TEMPLATE_NOT_FOUND_ERROR = 2000
    # users
    FAILED_TO_UPDATE_USER_ERROR = 3003
