GITHUB_OAUTH_HANDSHAKE_COOKIE_NAME = "qernel_github_oauth_handshake"
GITHUB_OAUTH_HANDSHAKE_TTL_SECONDS = 600  # 10 minutes
SESSION_COOKIE_NAME = "qernel_session"
SESSION_TTL_SECONDS = 604800  # 7 days
